# Generated by Django 4.2.30 on 2026-04-14 11:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('trips', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='itineraryitem',
            options={'ordering': ['start_time']},
        ),
        migrations.RenameField(
            model_name='document',
            old_name='title',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='expense',
            old_name='title',
            new_name='concept',
        ),
        migrations.RenameField(
            model_name='itineraryitem',
            old_name='time',
            new_name='end_time',
        ),
        migrations.RenameField(
            model_name='itineraryitem',
            old_name='location',
            new_name='location_text',
        ),
        migrations.RenameField(
            model_name='tripmembership',
            old_name='joined_at',
            new_name='created_at',
        ),
        migrations.AlterUniqueTogether(
            name='tripmembership',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='document',
            name='document_type',
        ),
        migrations.RemoveField(
            model_name='itineraryitem',
            name='date',
        ),
        migrations.RemoveField(
            model_name='itineraryitem',
            name='order',
        ),
        migrations.RemoveField(
            model_name='itineraryitem',
            name='trip',
        ),
        migrations.RemoveField(
            model_name='trip',
            name='description',
        ),
        migrations.RemoveField(
            model_name='trip',
            name='status',
        ),
        migrations.AddField(
            model_name='document',
            name='mime_type',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='expense',
            name='currency',
            field=models.CharField(default='EUR', max_length=3),
        ),
        migrations.AddField(
            model_name='expense',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='itineraryitem',
            name='estimated_cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='itineraryitem',
            name='item_type',
            field=models.CharField(choices=[('activity', 'Actividad'), ('transport', 'Transporte'), ('meal', 'Comida'), ('accommodation', 'Alojamiento'), ('other', 'Otro')], default='activity', max_length=20),
        ),
        migrations.AddField(
            model_name='itineraryitem',
            name='start_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='itineraryitem',
            name='status',
            field=models.CharField(choices=[('pending', 'Pendiente'), ('confirmed', 'Confirmado'), ('cancelled', 'Cancelado')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='trip',
            name='budget',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='trip',
            name='currency',
            field=models.CharField(choices=[('EUR', 'Euro'), ('USD', 'Dólar'), ('GBP', 'Libra esterlina'), ('JPY', 'Yen japonés'), ('MXN', 'Peso mexicano')], default='EUR', max_length=3),
        ),
        migrations.AddField(
            model_name='trip',
            name='travel_style',
            field=models.CharField(blank=True, choices=[('adventure', 'Aventura'), ('cultural', 'Cultural'), ('beach', 'Playa'), ('city', 'Ciudad'), ('nature', 'Naturaleza'), ('other', 'Otro')], max_length=20),
        ),
        migrations.AddField(
            model_name='tripmembership',
            name='expiration',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tripmembership',
            name='invited_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='tripmembership',
            name='status',
            field=models.CharField(choices=[('accepted', 'Aceptado'), ('pending', 'Pendiente'), ('rejected', 'Rechazado')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='tripmembership',
            name='token',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AlterField(
            model_name='tripmembership',
            name='role',
            field=models.CharField(choices=[('owner', 'Propietario'), ('editor', 'Editor'), ('viewer', 'Visualizador')], default='editor', max_length=20),
        ),
        migrations.AlterField(
            model_name='tripmembership',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='memberships', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='TripDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('day_index', models.PositiveIntegerField()),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='days', to='trips.trip')),
            ],
            options={
                'ordering': ['day_index'],
                'unique_together': {('trip', 'date')},
            },
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reservation_type', models.CharField(choices=[('flight', 'Vuelo'), ('hotel', 'Hotel'), ('car', 'Alquiler de coche'), ('activity', 'Actividad'), ('other', 'Otro')], max_length=20)),
                ('provider', models.CharField(max_length=200)),
                ('locator', models.CharField(blank=True, max_length=100)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='trips.trip')),
            ],
            options={
                'ordering': ['start_date'],
            },
        ),
        migrations.CreateModel(
            name='AIGeneration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parameters', models.JSONField(default=dict)),
                ('prompt', models.TextField()),
                ('response', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_generations', to='trips.trip')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='itineraryitem',
            name='day',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='trips.tripday'),
            preserve_default=False,
        ),
    ]
