# Generated by Django 4.2.30 on 2026-04-16 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0002_alter_itineraryitem_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tripmembership',
            name='role',
            field=models.CharField(choices=[('owner', 'Propietario'), ('invitado', 'Invitado')], default='invitado', max_length=20),
        ),
    ]
