# Generated by Django 4.2.30 on 2026-05-06 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0003_alter_tripmembership_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='date_end',
            field=models.DateField(blank=True, null=True),
        ),
    ]
