# Generated by Django 4.2.30 on 2026-05-18 11:38

from django.db import migrations


def setup_sites(apps, schema_editor):
    Site = apps.get_model('sites', 'Site')
    Site.objects.update_or_create(id=1, defaults={'domain': 'localhost:8000', 'name': 'PokeTrip local'})
    Site.objects.update_or_create(id=2, defaults={'domain': 'poketrip.es', 'name': 'PokeTrip'})


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0004_add_date_end_to_expense'),
        ('sites', '0002_alter_domain_unique'),
    ]

    operations = [
        migrations.RunPython(setup_sites, migrations.RunPython.noop),
    ]
